/* =========================================================
   CUSTOMER ANALYSIS
   ========================================================= */


/* =========================================================
   01. CUSTOMER BASE
   ========================================================= */

-- 01.1 TOTAL CUSTOMERS
SELECT
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;


-- 01.2 CUSTOMERS BY BUSINESS SEGMENT
SELECT
    CUSTOMER_SEGMENT,
    COUNT(DISTINCT CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY
    CUSTOMER_SEGMENT
ORDER BY
    NUMBER_OF_CUSTOMERS DESC;


-- 01.3 CUSTOMER SEGMENT DISTRIBUTION
WITH CUSTOMER_TOTAL AS (
    SELECT
        COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
    FROM CUSTOMERS
),
CUSTOMER_SEGMENTS AS (
    SELECT
        CUSTOMER_SEGMENT,
        COUNT(DISTINCT CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
    FROM CUSTOMERS
    GROUP BY
        CUSTOMER_SEGMENT
)
SELECT
    CS.CUSTOMER_SEGMENT,
    CS.NUMBER_OF_CUSTOMERS,
    ROUND(
        CAST(CS.NUMBER_OF_CUSTOMERS AS DECIMAL(10,2))
        / CT.TOTAL_CUSTOMERS * 100,
        2
    ) AS CUSTOMER_SEGMENT_DISTRIBUTION
FROM CUSTOMER_SEGMENTS CS
CROSS JOIN CUSTOMER_TOTAL CT
ORDER BY
    CUSTOMER_SEGMENT_DISTRIBUTION DESC;


/* =========================================================
   02. CUSTOMER VALUE
   ========================================================= */

-- 02.1 AVERAGE REVENUE PER CUSTOMER
SELECT
    ROUND(
        SUM(ORD.SALES_AMOUNT)
        / COUNT(DISTINCT O.CUSTOMER_ID),
        2
    ) AS AVERAGE_REVENUE_PER_CUSTOMER
FROM ORDERS O
JOIN ORDERS_DETAILS ORD
    ON O.ORDER_ID = ORD.ORDER_ID;


-- 02.2 CUSTOMER VALUE SEGMENTATION
WITH CUSTOMER_VALUE AS (
    SELECT
        O.CUSTOMER_ID,
        SUM(ORD.SALES_AMOUNT) AS CUSTOMER_REVENUE,
        COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS,
        RANK() OVER (
            ORDER BY SUM(ORD.SALES_AMOUNT) DESC
        ) AS CUSTOMER_RANK,
        NTILE(4) OVER (
            ORDER BY SUM(ORD.SALES_AMOUNT) DESC
        ) AS VALUE_QUARTILE
    FROM ORDERS O
    JOIN ORDERS_DETAILS ORD
        ON O.ORDER_ID = ORD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_REVENUE,
    NUMBER_OF_ORDERS,
    CUSTOMER_RANK,
    VALUE_QUARTILE,
    CASE
        WHEN VALUE_QUARTILE = 1
            THEN 'VERY HIGH VALUE'
        WHEN VALUE_QUARTILE = 2
            THEN 'HIGH VALUE'
        WHEN VALUE_QUARTILE = 3
            THEN 'LOW VALUE'
        ELSE 'VERY LOW VALUE'
    END AS CUSTOMER_VALUE_SEGMENT
FROM CUSTOMER_VALUE
ORDER BY
    CUSTOMER_RANK;


-- 02.3 CUSTOMER SEGMENT PERFORMANCE
WITH CUSTOMER_VALUE AS (
    SELECT
        O.CUSTOMER_ID,
        SUM(ORD.SALES_AMOUNT) AS CUSTOMER_REVENUE,
        COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS,
        NTILE(4) OVER (
            ORDER BY SUM(ORD.SALES_AMOUNT) DESC
        ) AS VALUE_QUARTILE
    FROM ORDERS O
    JOIN ORDERS_DETAILS ORD
        ON O.ORDER_ID = ORD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID
),
CUSTOMER_SEGMENTS AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_REVENUE,
        NUMBER_OF_ORDERS,
        CASE
            WHEN VALUE_QUARTILE = 1
                THEN 'VERY HIGH VALUE'
            WHEN VALUE_QUARTILE = 2
                THEN 'HIGH VALUE'
            WHEN VALUE_QUARTILE = 3
                THEN 'LOW VALUE'
            ELSE 'VERY LOW VALUE'
        END AS CUSTOMER_VALUE_SEGMENT
    FROM CUSTOMER_VALUE
)
SELECT
    CUSTOMER_VALUE_SEGMENT,
    COUNT(*) AS NUMBER_OF_CUSTOMERS,
    SUM(CUSTOMER_REVENUE) AS TOTAL_REVENUE,
    ROUND(AVG(CUSTOMER_REVENUE), 2) AS AVERAGE_REVENUE_PER_CUSTOMER,
    ROUND(AVG(NUMBER_OF_ORDERS), 2) AS AVERAGE_ORDERS_PER_CUSTOMER
FROM CUSTOMER_SEGMENTS
GROUP BY
    CUSTOMER_VALUE_SEGMENT
ORDER BY
    AVERAGE_REVENUE_PER_CUSTOMER DESC;


/* =========================================================
   03. CUSTOMER BEHAVIOR
   ========================================================= */

-- 03.1 AVERAGE ORDERS PER CUSTOMER
WITH CUSTOMER_ORDER_TOTALS AS (
    SELECT
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
    FROM ORDERS
)
SELECT
    TOTAL_ORDERS,
    TOTAL_CUSTOMERS,
    ROUND(
        CAST(TOTAL_ORDERS AS DECIMAL(10,2))
        / TOTAL_CUSTOMERS,
        2
    ) AS AVERAGE_ORDERS_PER_CUSTOMER
FROM CUSTOMER_ORDER_TOTALS;


-- 03.2 ORDERS PER CUSTOMER BY MONTH
SELECT
    YEAR(O.ORDER_DATE) AS ORDER_YEAR,
    MONTH(O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT O.CUSTOMER_ID) AS ACTIVE_CUSTOMERS,
    ROUND(
        CAST(COUNT(DISTINCT O.ORDER_ID) AS DECIMAL(10,2))
        / NULLIF(COUNT(DISTINCT O.CUSTOMER_ID), 0),
        2
    ) AS ORDERS_PER_CUSTOMER
FROM ORDERS O
GROUP BY
    YEAR(O.ORDER_DATE),
    MONTH(O.ORDER_DATE)
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;


-- 03.3 ONE-TIME VS REPEAT CUSTOMERS
WITH CUSTOMER_ORDER_COUNTS AS (
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT ORDER_ID) AS NUMBER_OF_ORDERS
    FROM ORDERS
    GROUP BY
        CUSTOMER_ID
)
SELECT
    SUM(
        CASE
            WHEN NUMBER_OF_ORDERS = 1 THEN 1
            ELSE 0
        END
    ) AS ONE_TIME_CUSTOMERS,
    SUM(
        CASE
            WHEN NUMBER_OF_ORDERS > 1 THEN 1
            ELSE 0
        END
    ) AS REPEAT_CUSTOMERS
FROM CUSTOMER_ORDER_COUNTS;


-- 03.4 REPEAT CUSTOMER RATE
WITH CUSTOMER_ORDER_COUNTS AS (
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT ORDER_ID) AS NUMBER_OF_ORDERS
    FROM ORDERS
    GROUP BY
        CUSTOMER_ID
)
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(
        CASE
            WHEN NUMBER_OF_ORDERS > 1 THEN 1
            ELSE 0
        END
    ) AS REPEAT_CUSTOMERS,
    ROUND(
        CAST(
            SUM(
                CASE
                    WHEN NUMBER_OF_ORDERS > 1 THEN 1
                    ELSE 0
                END
            ) AS DECIMAL(10,2)
        )
        / COUNT(*) * 100,
        2
    ) AS REPEAT_CUSTOMER_RATE
FROM CUSTOMER_ORDER_COUNTS;


-- 03.5 CUSTOMER AOV
SELECT
    O.CUSTOMER_ID,
    SUM(ORD.SALES_AMOUNT) AS CUSTOMER_REVENUE,
    COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS,
    ROUND(
        SUM(ORD.SALES_AMOUNT)
        / COUNT(DISTINCT O.ORDER_ID),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM ORDERS O
JOIN ORDERS_DETAILS ORD
    ON O.ORDER_ID = ORD.ORDER_ID
GROUP BY
    O.CUSTOMER_ID;


-- 03.6 CUSTOMER AOV BENCHMARKING
WITH CUSTOMER_METRICS AS (
    SELECT
        O.CUSTOMER_ID,
        SUM(ORD.SALES_AMOUNT) AS CUSTOMER_REVENUE,
        COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS,
        ROUND(
            SUM(ORD.SALES_AMOUNT)
            / COUNT(DISTINCT O.ORDER_ID),
            2
        ) AS AVERAGE_ORDER_VALUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS ORD
        ON O.ORDER_ID = ORD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID
),
CUSTOMER_BENCHMARK AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_REVENUE,
        NUMBER_OF_ORDERS,
        AVERAGE_ORDER_VALUE,
        AVG(AVERAGE_ORDER_VALUE) OVER () AS OVERALL_AVERAGE_AOV
    FROM CUSTOMER_METRICS
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_REVENUE,
    NUMBER_OF_ORDERS,
    AVERAGE_ORDER_VALUE,
    ROUND(OVERALL_AVERAGE_AOV, 2) AS OVERALL_AVERAGE_AOV,
    CASE
        WHEN AVERAGE_ORDER_VALUE > OVERALL_AVERAGE_AOV
            THEN 'ABOVE AVERAGE'
        ELSE 'BELOW AVERAGE'
    END AS AOV_CATEGORY
FROM CUSTOMER_BENCHMARK
ORDER BY
    AVERAGE_ORDER_VALUE DESC;


/* =========================================================
   04. CUSTOMER ENGAGEMENT
   ========================================================= */

-- 04.1 CUSTOMER RECENCY CLASSIFICATION
WITH CUSTOMER_RECENCY AS (
    SELECT
        CUSTOMER_ID,
        MAX(ORDER_DATE) AS MOST_RECENT_ORDER_DATE,
        DATEDIFF(
            DAY,
            MAX(ORDER_DATE),
            '2025-12-30'
        ) AS DAYS_SINCE_LAST_ORDER
    FROM ORDERS
    GROUP BY
        CUSTOMER_ID
)
SELECT
    CUSTOMER_ID,
    MOST_RECENT_ORDER_DATE,
    DAYS_SINCE_LAST_ORDER,
    CASE
        WHEN DAYS_SINCE_LAST_ORDER <= 1
            THEN 'VERY ACTIVE'
        WHEN DAYS_SINCE_LAST_ORDER BETWEEN 2 AND 4
            THEN 'ACTIVE'
        ELSE 'AT RISK'
    END AS CUSTOMER_RECENCY_CLASSIFICATION
FROM CUSTOMER_RECENCY
ORDER BY
    DAYS_SINCE_LAST_ORDER;


/* =========================================================
   05. CUSTOMER REVENUE CONCENTRATION
   ========================================================= */

-- 05.1 CUSTOMER REVENUE CONCENTRATION
WITH CUSTOMER_REVENUE AS (
    SELECT
        O.CUSTOMER_ID,
        SUM(ORD.SALES_AMOUNT) AS CUSTOMER_REVENUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS ORD
        ON O.ORDER_ID = ORD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID
),
TOTAL_REVENUE AS (
    SELECT
        SUM(SALES_AMOUNT) AS TOTAL_REVENUE
    FROM ORDERS_DETAILS
),
RANKED_CUSTOMERS AS (
    SELECT
        CR.CUSTOMER_ID,
        CR.CUSTOMER_REVENUE,
        TR.TOTAL_REVENUE,
        RANK() OVER (
            ORDER BY CR.CUSTOMER_REVENUE DESC
        ) AS CUSTOMER_RANK,
        SUM(CR.CUSTOMER_REVENUE) OVER (
            ORDER BY CR.CUSTOMER_REVENUE DESC
        ) AS CUMULATIVE_REVENUE
    FROM CUSTOMER_REVENUE CR
    CROSS JOIN TOTAL_REVENUE TR
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_REVENUE,
    CUSTOMER_RANK,
    ROUND(
        CUSTOMER_REVENUE / TOTAL_REVENUE * 100,
        2
    ) AS REVENUE_CONTRIBUTION,
    CUMULATIVE_REVENUE,
    ROUND(
        CUMULATIVE_REVENUE / TOTAL_REVENUE * 100,
        2
    ) AS CUMULATIVE_REVENUE_CONTRIBUTION
FROM RANKED_CUSTOMERS
ORDER BY
    CUSTOMER_RANK;