/* =========================================================
   EXECUTIVE BUSINESS KPIs
   ========================================================= */

-- KPI 01: GROSS SALES
SELECT
    SUM(SALES_AMOUNT) AS GROSS_SALES
FROM ORDERS_DETAILS;


-- KPI 02: COST OF GOODS SOLD
SELECT
    SUM(QUANTITY * COST_PRICE) AS COST_OF_GOODS_SOLD
FROM ORDERS_DETAILS;


-- KPI 03: GROSS PROFIT
SELECT
    SUM(SALES_AMOUNT)
    - SUM(QUANTITY * COST_PRICE) AS GROSS_PROFIT
FROM ORDERS_DETAILS;


-- KPI 04: GROSS MARGIN
SELECT
    ROUND(
        (
            SUM(SALES_AMOUNT)
            - SUM(QUANTITY * COST_PRICE)
        )
        / NULLIF(SUM(SALES_AMOUNT), 0) * 100,
        2
    ) AS GROSS_MARGIN_PERCENT
FROM ORDERS_DETAILS;


-- KPI 05: TOTAL ORDERS
SELECT
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;


-- KPI 06: TOTAL UNITS SOLD
SELECT
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM ORDERS_DETAILS;


-- KPI 07: AVERAGE ORDER VALUE
SELECT
    ROUND(
        SUM(SALES_AMOUNT)
        / NULLIF(COUNT(DISTINCT ORDER_ID), 0),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM ORDERS_DETAILS;


-- KPI 08: TOTAL CUSTOMERS
SELECT
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM ORDERS;


-- KPI 09: REVENUE PER CUSTOMER
SELECT
    ROUND(
        SUM(OD.SALES_AMOUNT)
        / NULLIF(COUNT(DISTINCT O.CUSTOMER_ID), 0),
        2
    ) AS REVENUE_PER_CUSTOMER
FROM ORDERS O
JOIN ORDERS_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID;