/* =========================================================
   PRODUCT ANALYSIS
   ========================================================= */


/* =========================================================
   01. PRODUCT BASE
   ========================================================= */

-- 01.1 TOTAL PRODUCTS
SELECT
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS
FROM PRODUCTS;


/* =========================================================
   02. PRODUCT SALES PERFORMANCE
   ========================================================= */

-- 02.1 REVENUE BY PRODUCT
SELECT
    P.PRODUCT_ID,
    SUM(OD.SALES_AMOUNT) AS PRODUCT_REVENUE
FROM PRODUCTS P
JOIN ORDERS_DETAILS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    PRODUCT_REVENUE DESC;


-- 02.2 TOP 10 PRODUCTS BY REVENUE
SELECT TOP 10
    P.PRODUCT_ID,
    SUM(OD.SALES_AMOUNT) AS PRODUCT_REVENUE
FROM PRODUCTS P
JOIN ORDERS_DETAILS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    PRODUCT_REVENUE DESC;


-- 02.3 BOTTOM 10 PRODUCTS BY REVENUE
SELECT TOP 10
    P.PRODUCT_ID,
    SUM(OD.SALES_AMOUNT) AS PRODUCT_REVENUE
FROM PRODUCTS P
JOIN ORDERS_DETAILS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    PRODUCT_REVENUE ASC;


/* =========================================================
   03. PRODUCT VOLUME
   ========================================================= */

-- 03.1 UNITS SOLD BY PRODUCT
SELECT
    PRODUCT_ID,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM ORDERS_DETAILS
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_UNITS_SOLD DESC;


-- 03.2 UNITS SOLD BY CATEGORY
SELECT
    P.CATEGORY,
    SUM(OD.QUANTITY) AS TOTAL_UNITS_SOLD
FROM PRODUCTS P
JOIN ORDERS_DETAILS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
    P.CATEGORY
ORDER BY
    TOTAL_UNITS_SOLD DESC;


-- 03.3 AVERAGE SELLING PRICE
SELECT
    ROUND(
        SUM(SALES_AMOUNT)
        / NULLIF(SUM(QUANTITY), 0),
        2
    ) AS AVERAGE_SELLING_PRICE
FROM ORDERS_DETAILS;


/* =========================================================
   04. PRODUCT RECENCY
   ========================================================= */

-- 04.1 PRODUCT ORDER RECENCY
SELECT
    OD.PRODUCT_ID,
    MAX(O.ORDER_DATE) AS MOST_RECENT_ORDER_DATE,
    DATEDIFF(
        DAY,
        MAX(O.ORDER_DATE),
        '2025-12-30'
    ) AS DAYS_SINCE_LAST_ORDER
FROM ORDERS O
JOIN ORDERS_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
    OD.PRODUCT_ID
ORDER BY
    DAYS_SINCE_LAST_ORDER;


/* =========================================================
   05. PRODUCT PROFITABILITY
   ========================================================= */

-- 05.1 PRODUCT PROFITABILITY
WITH PRODUCT_PROFITABILITY AS (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS PRODUCT_REVENUE,
        SUM(
            SALES_AMOUNT
            - (QUANTITY * COST_PRICE)
        ) AS GROSS_PROFIT
    FROM ORDERS_DETAILS
    GROUP BY
        PRODUCT_ID
)
SELECT
    PRODUCT_ID,
    PRODUCT_REVENUE,
    GROSS_PROFIT,
    ROUND(
        GROSS_PROFIT
        / NULLIF(PRODUCT_REVENUE, 0) * 100,
        2
    ) AS GROSS_MARGIN
FROM PRODUCT_PROFITABILITY
ORDER BY
    GROSS_PROFIT DESC;


-- 05.2 TOP 10 PRODUCTS BY GROSS PROFIT
SELECT TOP 10
    PRODUCT_ID,
    SUM(
        SALES_AMOUNT
        - (QUANTITY * COST_PRICE)
    ) AS GROSS_PROFIT
FROM ORDERS_DETAILS
GROUP BY
    PRODUCT_ID
ORDER BY
    GROSS_PROFIT DESC;


/* =========================================================
   06. PRODUCT REVENUE CONTRIBUTION
   ========================================================= */

-- 06.1 REVENUE CONTRIBUTION BY PRODUCT
WITH PRODUCT_REVENUE AS (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS PRODUCT_REVENUE
    FROM ORDERS_DETAILS
    GROUP BY
        PRODUCT_ID
),
TOTAL_REVENUE AS (
    SELECT
        SUM(SALES_AMOUNT) AS TOTAL_REVENUE
    FROM ORDERS_DETAILS
)
SELECT
    PR.PRODUCT_ID,
    PR.PRODUCT_REVENUE,
    ROUND(
        PR.PRODUCT_REVENUE
        / NULLIF(TR.TOTAL_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION
FROM PRODUCT_REVENUE PR
CROSS JOIN TOTAL_REVENUE TR
ORDER BY
    REVENUE_CONTRIBUTION DESC;


/* =========================================================
   07. PRODUCT REVENUE CONCENTRATION
   ========================================================= */

-- 07.1 PRODUCT REVENUE PARETO ANALYSIS
WITH PRODUCT_REVENUE AS (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS PRODUCT_REVENUE
    FROM ORDERS_DETAILS
    GROUP BY
        PRODUCT_ID
),
TOTAL_REVENUE AS (
    SELECT
        SUM(SALES_AMOUNT) AS TOTAL_REVENUE
    FROM ORDERS_DETAILS
),
RANKED_PRODUCTS AS (
    SELECT
        PR.PRODUCT_ID,
        PR.PRODUCT_REVENUE,
        TR.TOTAL_REVENUE,
        RANK() OVER (
            ORDER BY PR.PRODUCT_REVENUE DESC
        ) AS PRODUCT_REVENUE_RANK,
        SUM(PR.PRODUCT_REVENUE) OVER (
            ORDER BY PR.PRODUCT_REVENUE DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS CUMULATIVE_REVENUE
    FROM PRODUCT_REVENUE PR
    CROSS JOIN TOTAL_REVENUE TR
)
SELECT
    PRODUCT_ID,
    PRODUCT_REVENUE,
    PRODUCT_REVENUE_RANK,
    ROUND(
        PRODUCT_REVENUE
        / NULLIF(TOTAL_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION,
    CUMULATIVE_REVENUE,
    ROUND(
        CUMULATIVE_REVENUE
        / NULLIF(TOTAL_REVENUE, 0) * 100,
        2
    ) AS CUMULATIVE_REVENUE_CONTRIBUTION
FROM RANKED_PRODUCTS
ORDER BY
    PRODUCT_REVENUE_RANK;


/* =========================================================
   08. CATEGORY PROFITABILITY
   ========================================================= */

-- 08.1 CATEGORY PROFITABILITY
WITH CATEGORY_METRICS AS (
    SELECT
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT) AS CATEGORY_REVENUE,
        SUM(
            OD.SALES_AMOUNT
            - (OD.QUANTITY * OD.COST_PRICE)
        ) AS GROSS_PROFIT
    FROM PRODUCTS P
    JOIN ORDERS_DETAILS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY
        P.CATEGORY
)
SELECT
    CATEGORY,
    CATEGORY_REVENUE,
    GROSS_PROFIT,
    ROUND(
        GROSS_PROFIT
        / NULLIF(CATEGORY_REVENUE, 0) * 100,
        2
    ) AS GROSS_MARGIN
FROM CATEGORY_METRICS
ORDER BY
    GROSS_PROFIT DESC;


-- 08.2 CATEGORY REVENUE VS PROFIT CONTRIBUTION
WITH CATEGORY_METRICS AS (
    SELECT
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT) AS CATEGORY_REVENUE,
        SUM(
            OD.SALES_AMOUNT
            - (OD.QUANTITY * OD.COST_PRICE)
        ) AS GROSS_PROFIT
    FROM PRODUCTS P
    JOIN ORDERS_DETAILS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY
        P.CATEGORY
),
TOTAL_METRICS AS (
    SELECT
        SUM(SALES_AMOUNT) AS TOTAL_REVENUE,
        SUM(
            SALES_AMOUNT
            - (QUANTITY * COST_PRICE)
        ) AS TOTAL_GROSS_PROFIT
    FROM ORDERS_DETAILS
)
SELECT
    CM.CATEGORY,
    CM.CATEGORY_REVENUE,
    CM.GROSS_PROFIT,
    ROUND(
        CM.CATEGORY_REVENUE
        / NULLIF(TM.TOTAL_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION,
    ROUND(
        CM.GROSS_PROFIT
        / NULLIF(TM.TOTAL_GROSS_PROFIT, 0) * 100,
        2
    ) AS PROFIT_CONTRIBUTION,
    ROUND(
        CM.GROSS_PROFIT
        / NULLIF(CM.CATEGORY_REVENUE, 0) * 100,
        2
    ) AS GROSS_MARGIN
FROM CATEGORY_METRICS CM
CROSS JOIN TOTAL_METRICS TM
ORDER BY
    REVENUE_CONTRIBUTION DESC;