/* =========================================================
   REVENUE & GEOGRAPHIC ANALYSIS
   ========================================================= */


/* =========================================================
   01. REVENUE TRENDS
   ========================================================= */

-- 01.1 MONTHLY REVENUE

WITH MONTHLY_REVENUE AS (
    SELECT
        YEAR(O.ORDER_DATE) AS ORDER_YEAR,
        MONTH(O.ORDER_DATE) AS ORDER_MONTH,
        SUM(OD.SALES_AMOUNT) AS MONTHLY_REVENUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        YEAR(O.ORDER_DATE),
        MONTH(O.ORDER_DATE)
)
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    MONTHLY_REVENUE
FROM MONTHLY_REVENUE
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;


/* =========================================================
   01.2 MONTHLY REVENUE GROWTH
   ========================================================= */

WITH MONTHLY_REVENUE AS (
    SELECT
        YEAR(O.ORDER_DATE) AS ORDER_YEAR,
        MONTH(O.ORDER_DATE) AS ORDER_MONTH,
        SUM(OD.SALES_AMOUNT) AS MONTHLY_REVENUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        YEAR(O.ORDER_DATE),
        MONTH(O.ORDER_DATE)
),
REVENUE_COMPARISON AS (
    SELECT
        ORDER_YEAR,
        ORDER_MONTH,
        MONTHLY_REVENUE,
        LAG(MONTHLY_REVENUE) OVER (
            ORDER BY ORDER_YEAR, ORDER_MONTH
        ) AS PREVIOUS_MONTH_REVENUE
    FROM MONTHLY_REVENUE
)
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    MONTHLY_REVENUE,
    PREVIOUS_MONTH_REVENUE,
    ROUND(
        (
            MONTHLY_REVENUE
            - PREVIOUS_MONTH_REVENUE
        )
        / NULLIF(PREVIOUS_MONTH_REVENUE, 0) * 100,
        2
    ) AS REVENUE_GROWTH_RATE
FROM REVENUE_COMPARISON
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;


/* =========================================================
   01.3 MONTHLY REVENUE VARIANCE
   ========================================================= */

WITH MONTHLY_REVENUE AS (
    SELECT
        YEAR(O.ORDER_DATE) AS ORDER_YEAR,
        MONTH(O.ORDER_DATE) AS ORDER_MONTH,
        SUM(OD.SALES_AMOUNT) AS MONTHLY_REVENUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        YEAR(O.ORDER_DATE),
        MONTH(O.ORDER_DATE)
),
REVENUE_COMPARISON AS (
    SELECT
        ORDER_YEAR,
        ORDER_MONTH,
        MONTHLY_REVENUE,
        LAG(MONTHLY_REVENUE) OVER (
            ORDER BY ORDER_YEAR, ORDER_MONTH
        ) AS PREVIOUS_MONTH_REVENUE
    FROM MONTHLY_REVENUE
)
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    MONTHLY_REVENUE,
    PREVIOUS_MONTH_REVENUE,
    ROUND(
        MONTHLY_REVENUE
        - PREVIOUS_MONTH_REVENUE,
        2
    ) AS REVENUE_VARIANCE
FROM REVENUE_COMPARISON
ORDER BY
    ORDER_YEAR,
    ORDER_MONTH;


/* =========================================================
   02. REVENUE BY BUSINESS DIMENSION
   ========================================================= */

-- 02.1 REVENUE BY CUSTOMER SEGMENT

SELECT
    C.CUSTOMER_SEGMENT,
    COUNT(DISTINCT C.CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS,
    COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE,
    ROUND(
        SUM(OD.SALES_AMOUNT)
        / NULLIF(COUNT(DISTINCT O.ORDER_ID), 0),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDERS_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
    C.CUSTOMER_SEGMENT
ORDER BY
    TOTAL_REVENUE DESC;


-- 02.2 TOP PRODUCTS BY REVENUE

SELECT TOP 10
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(OD.SALES_AMOUNT) DESC
    ) AS REVENUE_RANK
FROM PRODUCTS P
JOIN ORDERS_DETAILS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY
    TOTAL_REVENUE DESC;


/* =========================================================
   03. CUSTOMER REVENUE PERFORMANCE
   ========================================================= */

-- 03.1 TOP 10 CUSTOMERS BY REVENUE

SELECT TOP 10
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_SEGMENT,
    SUM(OD.SALES_AMOUNT) AS CUSTOMER_REVENUE,
    RANK() OVER (
        ORDER BY SUM(OD.SALES_AMOUNT) DESC
    ) AS REVENUE_RANK
FROM ORDERS O
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN ORDERS_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_SEGMENT
ORDER BY
    CUSTOMER_REVENUE DESC;


-- 03.2 TOP CUSTOMER REVENUE CONTRIBUTION

WITH CUSTOMER_REVENUE AS (
    SELECT
        O.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.CUSTOMER_SEGMENT,
        SUM(OD.SALES_AMOUNT) AS CUSTOMER_REVENUE
    FROM ORDERS O
    JOIN CUSTOMERS C
        ON O.CUSTOMER_ID = C.CUSTOMER_ID
    JOIN ORDERS_DETAILS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        C.CUSTOMER_SEGMENT
),
TOTAL_REVENUE AS (
    SELECT
        SUM(CUSTOMER_REVENUE) AS TOTAL_REVENUE
    FROM CUSTOMER_REVENUE
)
SELECT TOP 10
    CR.CUSTOMER_ID,
    CR.CUSTOMER_NAME,
    CR.CUSTOMER_SEGMENT,
    CR.CUSTOMER_REVENUE,
    ROUND(
        CR.CUSTOMER_REVENUE
        / NULLIF(TR.TOTAL_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION
FROM CUSTOMER_REVENUE CR
CROSS JOIN TOTAL_REVENUE TR
ORDER BY
    CR.CUSTOMER_REVENUE DESC;


-- 03.3 TOP 10 CUSTOMER REVENUE CONCENTRATION

WITH CUSTOMER_REVENUE AS (
    SELECT
        O.CUSTOMER_ID,
        SUM(OD.SALES_AMOUNT) AS CUSTOMER_REVENUE
    FROM ORDERS O
    JOIN ORDERS_DETAILS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        O.CUSTOMER_ID
),
RANKED_CUSTOMERS AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_REVENUE,
        RANK() OVER (
            ORDER BY CUSTOMER_REVENUE DESC
        ) AS CUSTOMER_RANK
    FROM CUSTOMER_REVENUE
),
TOTAL_REVENUE AS (
    SELECT
        SUM(CUSTOMER_REVENUE) AS TOTAL_REVENUE
    FROM CUSTOMER_REVENUE
),
TOP_10_REVENUE AS (
    SELECT
        SUM(CUSTOMER_REVENUE) AS TOP_10_REVENUE
    FROM RANKED_CUSTOMERS
    WHERE CUSTOMER_RANK <= 10
)
SELECT
    TOP_10_REVENUE,
    TOTAL_REVENUE,
    ROUND(
        TOP_10_REVENUE
        / NULLIF(TOTAL_REVENUE, 0) * 100,
        2
    ) AS TOP_10_REVENUE_CONTRIBUTION
FROM TOP_10_REVENUE
CROSS JOIN TOTAL_REVENUE;


/* =========================================================
   04. GEOGRAPHIC REVENUE PERFORMANCE
   ========================================================= */

-- 04.1 REVENUE BY COUNTRY

SELECT
    TRIM(COUNTRY) AS COUNTRY,
    SUM([SALES AMOUNT]) AS TOTAL_REVENUE
FROM [OLE DB Destination]
GROUP BY
    TRIM(COUNTRY)
ORDER BY
    TOTAL_REVENUE DESC;


-- 04.2 REVENUE BY REGION

SELECT
    TRIM(REGION) AS REGION,
    SUM([SALES AMOUNT]) AS TOTAL_REVENUE
FROM [OLE DB Destination]
GROUP BY
    TRIM(REGION)
ORDER BY
    TOTAL_REVENUE DESC;


-- 04.3 REVENUE BY STATE

SELECT
    TRIM(STATE) AS STATE,
    SUM([SALES AMOUNT]) AS TOTAL_REVENUE
FROM [OLE DB Destination]
GROUP BY
    TRIM(STATE)
ORDER BY
    TOTAL_REVENUE DESC;

--============================================================
-- GEOGRAPHIC ANALYSIS
-- REVENUE CONTRIBUTION BY COUNTRY
--============================================================

WITH COUNTRY_REVENUE AS (
    SELECT
        TRIM([COUNTRY]) AS COUNTRY,
        SUM([SALES AMOUNT]) AS TOTAL_REVENUE
    FROM [OLE DB Destination]
    GROUP BY
        TRIM([COUNTRY])
),

TOTAL_REVENUE AS (
    SELECT
        SUM(TOTAL_REVENUE) AS COMPANY_REVENUE
    FROM COUNTRY_REVENUE
)

SELECT
    CR.COUNTRY,
    CR.TOTAL_REVENUE,

    ROUND(
        CAST(CR.TOTAL_REVENUE AS DECIMAL(18,2))
        / NULLIF(TR.COMPANY_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION_PCT

FROM COUNTRY_REVENUE CR

CROSS JOIN TOTAL_REVENUE TR

ORDER BY
    REVENUE_CONTRIBUTION_PCT DESC;


--============================================================
-- REVENUE CONTRIBUTION BY REGION
--============================================================

WITH REGION_REVENUE AS (
    SELECT
        TRIM([REGION]) AS REGION,
        SUM([SALES AMOUNT]) AS TOTAL_REVENUE
    FROM [OLE DB Destination]
    GROUP BY
        TRIM([REGION])
),

TOTAL_REVENUE AS (
    SELECT
        SUM(TOTAL_REVENUE) AS COMPANY_REVENUE
    FROM REGION_REVENUE
)

SELECT
    RR.REGION,
    RR.TOTAL_REVENUE,

    ROUND(
        CAST(RR.TOTAL_REVENUE AS DECIMAL(18,2))
        / NULLIF(TR.COMPANY_REVENUE, 0) * 100,
        2
    ) AS REVENUE_CONTRIBUTION_PCT

FROM REGION_REVENUE RR

CROSS JOIN TOTAL_REVENUE TR

ORDER BY
    REVENUE_CONTRIBUTION_PCT DESC;


-- ============================================================
-- TOP & BOTTOM GEOGRAPHIC MARKETS
-- STATE LEVEL
-- ============================================================

WITH STATE_REVENUE AS (
    SELECT
        TRIM([STATE]) AS STATE,
        SUM([SALES AMOUNT]) AS TOTAL_REVENUE
    FROM [OLE DB Destination]
    GROUP BY
        TRIM([STATE])
),

RANKED_STATES AS (
    SELECT
        STATE,
        TOTAL_REVENUE,

        RANK() OVER (
            ORDER BY TOTAL_REVENUE DESC
        ) AS REVENUE_RANK_DESC,

        RANK() OVER (
            ORDER BY TOTAL_REVENUE ASC
        ) AS REVENUE_RANK_ASC

    FROM STATE_REVENUE
)

SELECT
    STATE,
    TOTAL_REVENUE,
    REVENUE_RANK_DESC,
    REVENUE_RANK_ASC,

    CASE
        WHEN REVENUE_RANK_DESC <= 10
            THEN 'TOP MARKET'

        WHEN REVENUE_RANK_ASC <= 10
            THEN 'BOTTOM MARKET'

        ELSE 'MID-TIER MARKET'
    END AS MARKET_CLASSIFICATION

FROM RANKED_STATES

ORDER BY
    TOTAL_REVENUE DESC;


